### PR TITLE
fix: MultiAliasImportRequireUse collection and false positive

### LINKED ISSUE #1023: False positive on MultiAliasImportRequireUse when using multiple modules in same file
### Precheck

* Proposals for new features should be submitted via: https://github.com/rrrene/credo-proposals
* For bugs, please do a quick search and make sure the bug has not yet been reported here
   * I have not found any other issue about MultiAlias used in files with multiple modules

### Environment

* Credo version (`mix credo -v`): 1.6.7
* Erlang/Elixir version (`elixir -v`): 1.13.4-otp-25 and 1.12.3-otp-24
* Operating system: Ubuntu 22 and macOS Ventura

### What were you trying to do?

Example repository: https://github.com/ZeLarpMaster/CredoMultiAliasExample

TL;DR in a single file:

```elixir
defmodule CredoMultiAliasExample.Bar do
  @moduledoc "This module aliases another module"

  alias CredoMultiAliasExample.Foo
end

defmodule CredoMultiAliasExample.Baz do
  @moduledoc "This module aliases a different module under the same parent"

  alias CredoMultiAliasExample.Bar
end
```

Moving the 2nd `defmodule` into its own file fixes the issue even though that's effectively the same thing.

### Expected outcome

No issues found

### Actual outcome

>   Consistency
┃
┃ [C] ↗ Most of the time you are using the multi-alias/require/import/use syntax, but here you are using multiple single
┃       directives
┃       lib/credo_multi_alias_example.ex:16 #(CredoMultiAliasExample.Baz)

### PR DESCRIPTION
**Pull request by msutkowski**
Fixes #1023 

When you have files that contain multiple modules this rule will raise a false positive and force a user to disable the rule for the file. These changes solve that, but they _do not_ solve the issue where you have mixed usage in just a single file. We could do that, but the scope was increase quite a bit and most likely isn't super important.

### CODE REVIEW

File: test/credo/check/consistency/multi_alias_import_require_use_test.exs [hunk 1]
```diff
@@ -50,6 +83,13 @@ defmodule Credo.Check.Consistency.MultiAliasImportRequireUseTest do
     |> refute_issues()
   end
 
+  test "it should not report errors when the single syntax is used consistently" do
+    [@single]
+    |> to_source_files
+    |> run_check(@described_check)
+    |> refute_issues()
+  end
```
Comment (msutkowski) [inline test/credo/check/consistency/multi_alias_import_require_use_test.exs:91]: This is just moved up - it was in the wrong section.

**Comment by rrrene** [comment]
@msutkowski Thx!
